version: "3.8"
services:
  nginx:
    build: ./nginx
    volumes:
      - './project/public:/app/public'
    ports:
      - '3100:80'
    depends_on:
      - app
  app:
    build: ./app
    volumes:
      - './project:/app'
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: xm
      POSTGRES_PASSWORD: xm
      POSTGRES_USER: xm
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '3101:5432'
volumes:
  db-data:
  rm-data: