version: "3.8"
services:
  nginx:
    build: ./nginx
    volumes:
      - './project/public:/app/public'
    ports:
      - '3100:80'
    depends_on:
      - app
  app:
    build: ./app
    volumes:
      - './project:/app'
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: xm
      POSTGRES_PASSWORD: xm
      POSTGRES_USER: xm
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '3101:5432'
  rabbitmq:
    image: rabbitmq:3.11.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: xm
      RABBITMQ_DEFAULT_PASS: xm
    volumes:
      - rm-data:/var/lib/rabbitmq/mnesia
    ports:
      - "3102:5672"
      - "3103:15672"
volumes:
  db-data:
  rm-data: